name: "Deploy Dev"

on:
  push:
    # branches: [main]
    paths:
      - "infrastructure/**"
  pull_request:
    paths:
      - "infrastructure/**"

jobs:
  dev:
    uses: ./terraform-ci-template.yml
    with:
      environment: dev
      aws_region: ${{ secrets.DEV_AWS_REGION }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.DEV_AWS_ROLE_ARN }}
      AWS_TFSTATE_BUCKET: ${{ secrets.DEV_AWS_TFSTATE_BUCKET }}